FROM node:current-bullseye AS builder

WORKDIR /app

# ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json .
RUN npm ci

COPY . .

RUN npm run build

# ---- Production stage ----
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]